# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15613f41e980f1446c493f556282cacaaa9bf6891c2da9dcb5c850f46458cfb7a07959e7ea88d23f17b6c56b041f9c38d545f3389babf9adda82ac68dc283275

test:
  secret_key_base: 1af7b2f9d1d72e1fd59b03b2922d27a838516013f20446e0f09601c39eaa198d97528bbb90425e73300b50633f389965cc50ba7f1325d1f446367dcff09211fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
